status = [
  "ci/circleci: firefox-build-and-deploy",
  "ci/circleci: docker-build-and-deploy",
  "ci/circleci: rust-build-and-deploy",
  "ci/circleci: python-node-build-and-deploy",
]
cut_body_after = "\n\n---\n\n" # Avoid including verbose details from Renovate in commit messages
block_labels = ["bors-dont-merge"]
# At the moment, this project is a single-developer project.
# Increase this to 1 when the project has more developers.
required_approvals = 0
delete_merged_branches = true
